use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use clap::Parser;
use reanim_parser::ReanimatorDefinition;
use reanim_renderer::find_anim_masks;

#[derive(Parser)]
#[command(name = "reanim_makefile_gen")]
struct Cli {
    /// Directory containing .reanim files
    #[arg(long)]
    reanim: PathBuf,
    /// Output path for the generated Makefile
    #[arg(long)]
    makefile_output: PathBuf,
    /// Output directory for GIF files
    #[arg(long)]
    gif_output: PathBuf,
}

fn discover_reanim_files(dir: &Path) -> Result<Vec<PathBuf>> {
    let mut files = Vec::new();
    let read_dir = std::fs::read_dir(dir)
        .with_context(|| format!("Failed to read directory: {}", dir.display()))?;

    for entry in read_dir {
        let entry = entry?;
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) == Some("reanim") {
            files.push(path);
        }
    }

    files.sort();
    Ok(files)
}

struct ReanimFileInfo {
    stem: String,
    masks: Vec<String>,
}

fn analyze_reanim_file(path: &Path) -> Result<ReanimFileInfo> {
    let stem = path
        .file_stem()
        .and_then(|s| s.to_str())
        .context("Invalid file name")?
        .to_string();

    let def = ReanimatorDefinition::from_file(path)
        .with_context(|| format!("Failed to parse: {}", path.display()))?;

    let masks = find_anim_masks(&def);
    let mask_names: Vec<String> = masks.into_iter().map(|m| m.name).collect();

    Ok(ReanimFileInfo {
        stem,
        masks: mask_names,
    })
}

fn generate_makefile(
    makefile_path: &Path,
    reanim_dir: &Path,
    gif_output: &Path,
    files: &[ReanimFileInfo],
) -> Result<()> {
    let reanim_dir_esc = reanim_dir.to_string_lossy();
    let gif_output_esc = gif_output.to_string_lossy();

    let mut content = String::new();
    content.push_str("# Generated by reanim_makefile_gen \u{2014} do not edit manually\n");
    content.push_str("\n");
    content.push_str(&format!("REANIM_DIR := {}\n", reanim_dir_esc));
    content.push_str(&format!("GIF_OUTPUT := {}\n", gif_output_esc));
    content.push_str("BIN := pvz-reanim-rs\n");
    content.push_str("\n");

    if files.is_empty() {
        content.push_str(".PHONY: all\n");
        content.push_str("all:\n");
        content.push_str("\t@echo \"No .reanim files to build.\"\n");
    } else {
        // all target
        content.push_str(".PHONY: all\n");
        content.push_str("all:");
        for info in files {
            content.push_str(&format!(" $(GIF_OUTPUT)/{}/.keep", info.stem));
        }
        content.push_str("\n");
        content.push_str("\n");

        // per-file rules
        for info in files {
            let stem = &info.stem;
            content.push_str(&format!(
                "$(GIF_OUTPUT)/{stem}/.keep: $(REANIM_DIR)/{stem}.reanim $(REANIM_DIR)/*.png\n"
            ));
            content.push_str("\tmkdir -p $(dir $@)\n");
            content.push_str(&format!(
                "\t$(BIN) \"$<\" \"$(dir $@){stem}\"\n"
            ));
            content.push_str("\ttouch \"$@\"\n");
            content.push_str("\n");
        }
    }

    if let Some(parent) = makefile_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(makefile_path, content)
        .with_context(|| format!("Failed to write Makefile to {}", makefile_path.display()))?;

    Ok(())
}

fn main() -> Result<()> {
    let args = Cli::parse();

    let reanim_files = discover_reanim_files(&args.reanim)?;

    if reanim_files.is_empty() {
        eprintln!(
            "Warning: no .reanim files found in {}",
            args.reanim.display()
        );
    }

    let mut file_infos = Vec::new();
    for path in &reanim_files {
        match analyze_reanim_file(path) {
            Ok(info) => {
                eprintln!("  {}: {} masks", info.stem, info.masks.len());
                file_infos.push(info);
            }
            Err(e) => {
                eprintln!("Warning: skipping {}: {e}", path.display());
            }
        }
    }

    eprintln!("Found {} valid .reanim file(s)", file_infos.len());

    generate_makefile(
        &args.makefile_output,
        &args.reanim,
        &args.gif_output,
        &file_infos,
    )?;

    eprintln!("Makefile written to: {}", args.makefile_output.display());

    Ok(())
}
